
#服务prot 集群:

server:
  port: 8100
#eureka基本信息


eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1

    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
        ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
  client:
  #
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true

###因为自己是为注册中心，不需要检索服务
    fetch-registry: true
  server:

        # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false

    eviction-interval-timer-in-ms: 2000


    ##集群名称相同.
spring:
  application:
    name: server_name





